name: Build OrangeFox Recovery

on:
  workflow_dispatch:
    inputs:
      MANIFEST_BRANCH:
        description: 'fox_12.0'
        required: true
        default: 'fox_12.0'
        type: choice
        options:
          - fox_12.0
          - fox_12.1
          - fox_11.0
      DEVICE_TREE:
        description: 'https://github.com/ibadriansyah/device_xiaomi_redwood.git'
        required: true
        type: string
      DEVICE_TREE_BRANCH:
        description: 'yaap-sixteen'
        required: true
        default: 'yaap-sixteen'
        type: string
      DEVICE_PATH:
        description: 'device/xiaomi/redwood'
        required: true
        type: string
      DEVICE_NAME:
        description: 'redwood'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Free Up Disk Space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: true

      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5 libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc yasm zip zlib1g-dev

      - name: Install Repo Tool
        run: |
          mkdir -p ~/.bin
          PATH="${HOME}/.bin:${PATH}"
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/.bin/repo
          chmod a+rx ~/.bin/repo

      - name: Initialize OrangeFox Source
        run: |
          mkdir workspace
          cd workspace
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          ~/.bin/repo init -u https://gitlab.com/OrangeFox/manifest.git -b ${{ inputs.MANIFEST_BRANCH }} --depth=1
          ~/.bin/repo sync -j$(nproc --all) --force-sync

      - name: Clone Device Tree
        run: |
          cd workspace
          git clone ${{ inputs.DEVICE_TREE }} -b ${{ inputs.DEVICE_TREE_BRANCH }} ${{ inputs.DEVICE_PATH }}

      - name: Start Building OrangeFox
        run: |
          cd workspace
          export ALLOW_MISSING_DEPENDENCIES=true
          source build/envsetup.sh
          lunch fox_${{ inputs.DEVICE_NAME }}-eng && mka bootimage

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: OrangeFox-${{ inputs.DEVICE_NAME }}-boot
          path: workspace/out/target/product/${{ inputs.DEVICE_NAME }}/boot.img

